#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "Running pre-commit hook..."

npx lint-staged
if [ $? -ne 0 ]; then
    echo "Error: npx command failed"
    exit 1
else
    echo "npx command succeeded"
fi

echo "Pre-commit hook completed."